### ISSUE TITLE
could you provide the hardware of the dock

### ISSUE THREAD

**Issue by yuduo** [SynapseProgramming/lidar_auto_docking#12]
could you please tell us the logic of using lidar docking?
so we here can make a dock and a robot test it

**Comment by SynapseProgramming** [comment]
Hi. Hang tight :) I will upload a readme file soon which would explain how to use this package.

**Comment by SynapseProgramming** [comment]
Hi, I have added in a readme file. Please give it a shot. Will close this issue for now.
