### ISSUE TITLE
Does not compile

### ISSUE THREAD

**Issue by GoktugGurler95** [SynapseProgramming/lidar_auto_docking#18]
colcon build
Starting >>> lidar_auto_docking
--- stderr: lidar_auto_docking                         
CMake Error at CMakeLists.txt:35 (find_package):
  By not providing "Findlidar_auto_docking_messages.cmake" in
  CMAKE_MODULE_PATH this project has asked CMake to find a package
  configuration file provided by "lidar_auto_docking_messages", but CMake did
  not find one.

  Could not find a package configuration file provided by
  "lidar_auto_docking_messages" with any of the following names:

    lidar_auto_docking_messagesConfig.cmake
    lidar_auto_docking_messages-config.cmake

  Add the installation prefix of "lidar_auto_docking_messages" to
  CMAKE_PREFIX_PATH or set "lidar_auto_docking_messages_DIR" to a directory
  containing one of the above files.  If "lidar_auto_docking_messages"
  provides a separate development package or SDK, be sure it has been
  installed.

gmake: *** [Makefile:513: cmake_check_build_system] Error 1
---
Failed   <<< lidar_auto_docking [2.68s, exited with code 2]

Summary: 0 packages finished [3.10s]
  1 package failed: lidar_auto_docking
  1 package had stderr output: lidar_auto_docking

**Comment by SynapseProgramming** [comment]
Hi, please install the lidar auto docking messages package first: 

git clone https://github.com/SynapseProgramming/lidar_auto_docking_messages.git

**Comment by GoktugGurler95** [comment]
sorry i didn't see it :D. Which robot model did you work on? Thank you

**Comment by SynapseProgramming** [comment]
I have tested this package on custom robots running ros2 and labview (for low level control)
